FROM node:20-alpine
WORKDIR /runner
ENV NODE_ENV=production
RUN apk add --no-cache docker-cli
RUN docker --version

COPY apps/runner/package.json ./package.json
COPY apps/runner/src ./src

EXPOSE 5099
CMD ["node", "src/server.js"]
